const Method = {
    POST: 'POST',
    GET: 'GET',
    PUT: 'PUT',
    DELETE: 'DELETE'
};

const HttpHeaders = {
    ACCEPT: 'application/json',
    CONTENT_TYPE: 'application/json; charset=utf-8'
};

const Actions = {
    units: {
        GET_UNITS_REQUEST: 'GET_UNITS_REQUEST',
        GET_UNITS_REQUEST_PENDING: 'GET_UNITS_REQUEST_PENDING',
        GET_UNITS_SUCCESS: 'GET_UNITS_SUCCESS',
        GET_UNITS_FAILED: 'GET_UNITS_FAILED',
        POST_UNIT_REQUEST: 'POST_UNIT_REQUEST',
        POST_UNIT_REQUEST_PENDING: 'POST_UNIT_REQUEST_PENDING',
        POST_UNIT_SUCCESS: 'POST_UNIT_SUCCESS',
        POST_UNIT_FAILED: 'POST_UNIT_FAILED'
    },
    ingredients: {
        GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST',
        GET_INGREDIENTS_REQUEST_PENDING: 'GET_INGREDIENTS_REQUEST_PENDING',
        GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS',
        GET_INGREDIENT_FAILED: 'GET_INGREDIENT_FAILED',
        POST_INGREDIENT_REQUEST: 'POST_INGREDIENT_REQUEST',
        POST_INGREDIENT_REQUEST_PENDING: 'POST_INGREDIENT_REQUEST_PENDING',
        POST_INGREDIENT_SUCCESS: 'POST_INGREDIENT_SUCCESS',
        POST_INGREDIENT_FAILED: 'POST_INGREDIENT_FAILED'
    },
    recipes: {
        GET_RECIPES_REQUEST: 'GET_RECIPES_REQUEST',
        GET_RECIPES_REQUEST_PENDING: 'GET_RECIPES_REQUEST_PENDING',
        GET_RECIPES_SUCCESS: 'GET_RECIPES_SUCCESS',
        GET_RECIPES_FAILED: 'GET_RECIPES_FAILED',
        POST_RECIPE_REQUEST: 'POST_RECIPE_REQUEST',
        POST_RECIPE_REQUEST_PENDING: 'POST_RECIPE_REQUEST_PENDING',
        POST_RECIPE_SUCCESS: 'POST_RECIPE_SUCCESS',
        POST_RECIPE_FAILED: 'POST_RECIPE_FAILED'
    },
    error: {
        UNEXPECTED_SERVER_ERROR: 'UNEXPECTED_SERVER_ERROR',
        UNEXPECTED_RESPONSE: 'UNEXPECTED_RESPONSE'
    }
};

export {
    Method,
    HttpHeaders,
    Actions
};