version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - timestamp="`date +%s%N`"
      - npm install
      - npm run build
      - cd dist
      - mkdir robbie
      - cd robbie
      - touch file.txt
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'