version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - timestamp="`date +%s%N`"
      - cd api
      - mvn package
      - aws s3 cp target/chow-down-api.jar s3://${ChowDownApiSourceBucket}/chow-down-api-build-${timestamp}.jar
      - sed -ie "s/%{ChowDownApiSourceKey}/chow-down-api-build-${timestamp}.jar/g" cloudformation/stack-template.yml
      - aws s3 cp swagger.yml s3://${ChowDownApiSourceBucket}/chow-down-api-swagger-${timestamp}.yml
      - sed -ie "s/%{ChowDownApiSwaggerKey}/chow-down-api-swagger-${timestamp}.yml/g" cloudformation/stack-template.yml
artifacts:
  files:
    - cloudformation/**/*