AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DB Test for Chow
Resources:
  ChowDbPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "rob"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
  ChowDb:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: chowtestrob
      DBClusterIdentifier: chow-test-rob-cluster
      DeletionProtection: true
      Engine: aurora-postgresql
      EngineMode: serverless
      EngineVersion: 10.7
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref ChowDbPassword, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref ChowDbPassword, ':SecretString:password}}' ]]
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 2
        SecondsUntilAutoPause: 900
  ChowDbPasswordAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref ChowDbPassword
      TargetId: !Ref ChowDb
      TargetType: AWS::RDS::DBCluster
  # MySecretResourcePolicy:
  #   Type: AWS::SecretsManager::ResourcePolicy
  #   Properties:
  #     SecretId: !Ref ChowDbPassword
  #     ResourcePolicy: 
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Deny
  #           Principal: 
  #             AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  #           Action: secretsmanager:DeleteSecret
  #           Resource: "*"