version: "3.6"

services:
  chow-db:
    image: postgres:11.3-alpine
    ports:
      - 5432:5432
    networks:
      - chow-net
    volumes:
      - ./chow-db:/var/lib/postgresql/data/chow-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chow-db
      - PGDATA=/var/lib/postgresql/data/chow-db
  pg-admin:
    image: dpage/pgadmin4:4.8
    ports:
      - 9090:80
    networks:
      - chow-net
    volumes:
      - ./postgres-server.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}

networks:
  chow-net: